// Code generated by Vanya: DO NOT EDIT.
// versions:
// 	vanya v0.0.0
// source: github.com/ivanmashin/my-service/configs/config.go

//go:generate go run github.com/ivanmashin/vanya/cmd/config
//go:build !vanya
// +build !vanya

package single_obj

import "github.com/ivanmashin/vanya/pkg/configs"

type Config struct {
	configs.Embedding

	HttpEndpoint       string `mapstructure:"http_endpoint"`
	GrpcEndpoint       string `mapstructure:"grpc_endpoint"`
	MonitoringEndpoint string `mapstructure:"monitoring_endpoint"`
}

func NewConfig(opts ...configs.Option) (Config, error) {
	c := NewDefaultConfig()

	err := c.Init(&c, opts...)
	if err != nil {
		return Config{}, err
	}

	return c, nil
}

func NewDefaultConfig() Config {
	return Config{
		Embedding: configs.Embedding{},

		HttpEndpoint:       "localhost:51000",
		GrpcEndpoint:       "localhost:52000",
		MonitoringEndpoint: "localhost:53000",
	}
}
